### ISSUE TITLE
About LPversion and LPhelp

### ISSUE THREAD

**Issue by guyskk** [opticspy/lightpipes#20]
`from LightPipes import *` isn't good practice in python, although it seems nicer in this project, I prefer
`import LightPipes as lp` because it follows the convention of most python libraries.

The biggest problem of `import *` is it will pollute global namespace, we can add [\_\_all\_\_](https://docs.python.org/2/tutorial/modules.html#importing-from-a-package) to
`__init__.py`  to avoid this(LPversion and LPhelp look ugly).

Do you prefer convenience or comprehensive?

**Comment by FredvanGoor** [comment]
I agree, but I think that we have to choose for 'from LightPipes import * ', unless you have a better idea to use 'import LightPipes'. It is also good for the html creation because the 'command-reference' in docs looks nicer.
I continue to work on docs and examples. Furthermore I have an idea to put the version number in only one place and to change the LightPipes test method (it is LPtest now in stead of LPversion). The version number  appears in 'setup.py' and also in docs/conf.py and is displayed in the html. Now the version number is automatically adjusted in all files. It is in the 'GitHub master' already. Please have a look.
LPversion and LPHelp look ugly indeed but version and help are standard in Python.

**Comment by guyskk** [comment]
OK, I agree `from LightPipes import *`.
But do we really need `LPDoc` and `LPweb`?

**Comment by FredvanGoor** [comment]
I removed LPDoc and LPWeb ...
